apiVersion: v2
name: meshery
description: Meshery chart for deploying Meshery and Meshery's adapters.
icon: https://meshery.io/images/logos/meshery-logo.png
kubeVersion:
keywords:
  - meshery
  - meshery-istio
  - meshery-linkerd
  - meshery-consul
  - meshery-kuma
  - meshery-osm
  - meshery-nsm
  - meshery-traefik-mesh
  - meshery-cpx
  - meshery-nginx-sm
  - meshery-app-mesh
  - meshery-operator
  - meshery-broker
  - meshery-meshsync
source:
  - https://github.com/layer5io/meshery

engine: gotpl

deprecated: false

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.5.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
# TODO: Need to confirm the image version
# appVersion: v0.6.0



maintainers:
  - name: Layer5 Authors
    email: community@layer5.io
  - name: aisuko
    email: urakiny@gmail.com
  - name: leecalcote
    email: lee.calcote@layer5.io
  - name: darrenlau
    email: panyuenlau@gmail.com