version: "3"
services:
  meshery:
    image: layer5/meshery:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - "PROVIDER_BASE_URLS=https://meshery.layer5.io"
      - "SAAS_BASE_URL=https://meshery.layer5.io"
      - "ADAPTER_URLS=meshery-istio:10000 meshery-linkerd:10001 meshery-consul:10002 meshery-nsm:10004 meshery-app-mesh:10005 meshery-kuma:10007 meshery-osm:10009 meshery-traefik-mesh:10006 meshery-nginx-sm:10010 meshery-cilium:10012"
      - "EVENT=mesheryLocal"
      - "PORT=9081"
    volumes:
      - $HOME/.kube:/home/appuser/.kube:ro
      - $HOME/.minikube:$HOME/.minikube:ro
    ports:
      - "9081:9081"
  meshery-istio:
    image: layer5/meshery-istio:stable-latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "10000:10000"
  meshery-linkerd:
    image: layer5/meshery-linkerd:stable-latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "10001:10001"
  meshery-consul:
    image: layer5/meshery-consul:stable-latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "10002:10002"
  meshery-nsm:
    image: layer5/meshery-nsm:stable-latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "10004:10004"
  meshery-app-mesh:
    image: layer5/meshery-app-mesh:stable-latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "10005:10005"
  meshery-traefik-mesh:
    image: layer5/meshery-traefik-mesh:stable-latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "10006:10006"
  meshery-kuma:
    image: layer5/meshery-kuma:stable-latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "10007:10007"
  meshery-osm:
    image: layer5/meshery-osm:stable-latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "10009:10009"
  meshery-nginx-sm:
    image: layer5/meshery-nginx-sm:stable-latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "10010:10010"
  meshery-cilium:
    image: layer5/meshery-cilium:stable-latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "10012:10012"
  # nighthawk-lg:
  #   image: envoyproxy/nighthawk-dev:latest
  watchtower:
    image: containrrr/watchtower
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --label-enable
volumes:
  meshery-config:

