contexts:
    gke:
        endpoint: http://localhost:9081
        token: default
        platform: gke
        components:
            - meshery-istio
        channel: stable
        version: latest
    local:
        endpoint: http://localhost:9081
        token: default
        platform: docker
        components:
            - meshery-istio
        channel: stable
        version: latest
current-context: local
log_level: 4
tokens:
    - location: auth.json
      name: default
