contexts:
  local:
    endpoint: http://localhost:9081
    token: Default
    platform: docker
    adapters:
      - meshery-istio
    channel: stable
    version: v0.5.0-beta-1
  gke:
    endpoint: http://localhost:9081
    token: Default
    platform: gke
    adapters:
      - meshery-istio
    channel: stable
    version: v0.4.2

current-context: local

tokens:
- name: Default
  location: auth.json