{{- if and (not .Values.serviceAccountNameOverride) .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "meshery-traefik-mesh.serviceAccountName" . }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
{{- include "meshery-traefik-mesh.labels" . | nindent 4 }}
{{- end -}}
