apiVersion: v1
kind: Service
metadata:
  name: {{ include "meshery.name" . }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    {{- include "meshery.labels" . | nindent 4 }}
  annotations:
{{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.target_port }}
      protocol: TCP
      name: http
  selector:
    {{- include "meshery.selectorLabels" . | nindent 4 }}
