apiVersion: batch/v1
kind: Job
metadata:
  name: integration-test-meshsync-curl-upload-kubeconfig-job
spec:
  template:
    spec:
      containers:
      - name: curl-runner
        image: curlimages/curl:latest
        command: ["/bin/sh", "/scripts/curl-upload-kubeconfig.sh"]
        volumeMounts:
        - name: curl-upload-kubeconfig-script-volume
          mountPath: /scripts/curl-upload-kubeconfig.sh
          subPath: curl-upload-kubeconfig.sh
        - name: kubeconfig-volume
          mountPath: /configs/kubeconfig.yaml
          subPath: kubeconfig.yaml
      restartPolicy: Never
      volumes:
      - name: curl-upload-kubeconfig-script-volume 
        configMap:
          name: integration-test-meshsync-curl-upload-kubeconfig-script
      - name: kubeconfig-volume
        configMap:
          name: integration-test-meshsync-kubeconfig-file