apiVersion: v2
name: meshery
description: Meshery chart for deploying Meshery and Meshery's adapters.
icon: https://meshery.io/images/logos/meshery-logo.png
kubeVersion:
keywords:
  - meshery
  - meshery-istio
  - meshery-linkerd
  - meshery-consul
  - meshery-kuma
  - meshery-osm
  - meshery-nsm
  - meshery-traefik-mesh
  - meshery-nginx-sm
  - meshery-app-mesh
  - meshery-operator
  - meshery-broker
  - meshery-meshsync
source:
  - https://github.com/layer5io/meshery

engine: gotpl

deprecated: false

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.5.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
# TODO: Need to confirm the image version
# appVersion: v0.6.0

dependencies:
  - name: meshery-istio
    version: 0.5.0
    condition: meshery-istio.enabled
  - name: meshery-linkerd
    version: 0.5.0
    condition: meshery-linkerd.enabled
  - name: meshery-consul
    version: 0.5.0
    condition: meshery-consul.enabled
  - name: meshery-kuma
    version: 0.5.0
    condition: meshery-kuma.enabled
  - name: meshery-osm
    version: 0.5.0
    condition: meshery-osm.enabled
  - name: meshery-nsm
    version: 0.5.0
    condition: meshery-nsm.enabled
  - name: meshery-traefik-mesh
    version: 0.5.0
    condition: meshery-traefik-mesh.enabled
  - name: meshery-nginx-sm
    version: 0.5.0
    condition: meshery-nginx-sm.enabled
  - name: meshery-app-mesh
    version: 0.5.0
    condition: meshery-app-mesh.enabled
  - name: meshery-operator
    version: 0.5.0
    condition: meshery-operator.enabled
  - name: meshery-broker
    version: 0.5.0
    condition: meshery-broker.enabled
  - name: meshery-meshsync
    version: 0.5.0
    condition: meshery-meshsync.enabled
  - name: meshery-cilium
    version: 0.5.0
    condition: meshery-cilium.enabled

maintainers:
  - name: Meshery Authors
    email: maintainers@meshery.io
