# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Meshery Docs
email: community@layer5.io
description: 
  Documentation for Meshery, the multi-service mesh management plane for
  Istio, Linkerd, Consul, Network Service Mesh, Octarine, App Mesh and other service meshes.
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "https://meshery.layer5.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: layer5

# Build settings
markdown: kramdown
# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
plugins:
  - jekyll-feed


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# theme settings
search_enabled: true

# aux_links:
#     "Layer5":
#       - "//layer5.io/meshery"

ga_tracking: UA-2969471-4

exclude: ['Makefile']
