apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: meshery
  name: meshery
spec:
  selector:
    matchLabels:
      io.kompose.service: meshery
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: meshery
    spec:
      serviceAccountName: meshery-server
      containers:
        - env:
            - name: EVENT
              value: mesheryLocal
            - name: PROVIDER_BASE_URLS
              value: https://meshery.layer5.io
            - name: ADAPTER_URLS
              value: meshery-istio:10000 meshery-linkerd:10001 meshery-consul:10002 meshery-nsm:10004 meshery-app-mesh:10005 meshery-kuma:10007 meshery-cpx:10008 meshery-osm:10009 meshery-nginx-sm:10010
          image: layer5/meshery:stable-latest
          imagePullPolicy: Always
          name: meshery
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
