apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.32.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: meshery-nginx-sm
  name: meshery-nginx-sm
spec:
  selector:
    matchLabels:
      io.kompose.service: meshery-nginx-sm
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: meshery-nginx-sm
    spec:
      serviceAccount: meshery-server
      containers:
      - image: layer5/meshery-nginx-sm:stable-latest
        imagePullPolicy: Always
        name: meshery-nginx-sm
        ports:
        - containerPort: 10010
        resources: {}
      restartPolicy: Always
status: {}
