apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.32.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: meshery-kuma
  name: meshery-kuma
spec:
  ports:
    - name: "10007"
      port: 10007
      targetPort: 10007
  selector:
    io.kompose.service: meshery-kuma
status:
  loadBalancer: {}
