apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.32.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: meshery-app-mesh
  name: meshery-app-mesh
spec:
  selector:
    matchLabels:
      io.kompose.service: meshery-app-mesh
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: meshery-app-mesh
    spec:
      serviceAccount: meshery-server
      containers:
      - image: layer5/meshery-app-mesh:stable-latest
        imagePullPolicy: Always
        name: meshery-app-mesh
        ports:
        - containerPort: 10005
        resources: {}
      restartPolicy: Always
status: {}
