apiVersion: v1
kind: ServiceAccount
metadata:
  name: meshery-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meshery-server
  labels:
    app: meshery
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs: ["/metrics", "/health", "/ping"]
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: meshery-server
  labels:
    app: meshery
roleRef:
  kind: ClusterRole
  name: meshery-server
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: meshery-server
  namespace: meshery
---
