{{- if and (not .Values.serviceAccountNameOverride) .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "meshery-cpx.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "meshery-cpx.labels" . | nindent 4 }}
{{- end -}}
