name: Build and Preview Site
on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]
    paths:
      - '!**'
      - 'docs/**'
jobs:
  trigger-site-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@master
        with:
          persist-credentials: false
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.99.0
        with:
          ruby-version: 2.7.5 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install and Build ğŸ”§ 
        run: |
          cd docs
          make build
      - name: Zip Site
        run: bash docs/script.sh
      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          name: site-dir
          path: ./site-dir.zip
          retention-days: 1
      - name: Trigger Inner workflow
        run: echo "triggering workflow"
