name: Meshery Build and Push Docker Extension
on:
  # TODO :- Figure out a policy to build and push extension image to DockerHub
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'
      - '.github/**'
  workflow_dispatch:


jobs:
  build:
    name: Docker build and push
    if: github.repository == 'meshery/meshery'
    env:
      RELEASE_CHANNEL: "edge"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Delete default files present at project root
        run: |
          rm Dockerfile
          rm .dockerignore
      - name: Move files from ./install/docker-desktop-extension to project root
        run: |
          mv ./install/docker-desktop-extension/* ./
      - name: Docker login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker edge build & tag
        run: |
          DOCKER_BUILDKIT=1 docker build --no-cache -t meshery/meshery-docker-desktop-extension:edge-latest --build-arg TOKEN=${{ secrets.GLOBAL_TOKEN }} --build-arg GIT_COMMITSHA=${GITHUB_SHA::8} --build-arg GIT_VERSION="edge-latest" --build-arg RELEASE_CHANNEL=${RELEASE_CHANNEL} .
          docker tag meshery/meshery-docker-desktop-extension:edge-latest meshery/meshery-docker-desktop-extension:edge-${GITHUB_SHA::8}
      - name: Docker edge push
        run: |
          docker push meshery/meshery-docker-desktop-extension:edge-latest
          docker push meshery/meshery-docker-desktop-extension:edge-${GITHUB_SHA::8}
