name: Notify Meshery Extensions channel build
on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - 'v*'
jobs:
  notfiy-build:
    name: Notify providers for Meshery Extensions channel build
    if: github.repository == 'meshery/meshery'
    runs-on: ubuntu-22.04
    steps:
    - name: trigger plugins for edge
      uses: layer5io/trigger-remote-provider-action@master
      with:
        name: "Build and Rollout Kanvas"
        repo: layer5labs/meshery-extensions-packages
        token: ${{ secrets.GH_ACCESS_TOKEN }}
