name: Build and Preview Site
on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]
    paths:
      - '!**'
      - '!docs/meetings/**'
      - 'docs/**'
      
jobs:
  trigger-site-preview:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@master
        with:
          fetch-depth: 1
          persist-credentials: false
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.6 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      
      - name: Build mesheryctl cli reference
        run: |
          cd mesheryctl
          make docs
      
      - name: Install and Build
        run: |
          cd docs
          make build
      
      - name: Zip Site
        run: bash docs/script.sh
      
      - name: Upload files
        uses: actions/upload-artifact@v6
        with:
          name: site-dir
          path: ./site-dir.zip
          retention-days: 1
      
      - name: Trigger Inner workflow
        run: echo "triggering workflow"