name: Build and Preview Site
on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]
    paths:
      - '!**'
      - 'docs/**'
permissions:
  contents: read

jobs:
  trigger-site-preview:
    runs-on: ubuntu-22.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
        with:
          persist-credentials: false
      - name: Setup Ruby
        uses: ruby/setup-ruby@a6e6f86333f0a2523ece813039b8b4be04560854 # v1.190.0
        with:
          ruby-version: 3.2.2 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install and Build ğŸ”§ 
        run: |
          cd docs
          make build
      - name: Zip Site
        run: bash docs/script.sh
      - name: Upload files
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4.3.6
        with:
          name: site-dir
          path: ./site-dir.zip
          retention-days: 1
      - name: Trigger Inner workflow
        run: echo "triggering workflow"
