name: Discussion data files update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' #runs every day at midnight

jobs:
  update:
    runs-on: ubuntu-latest
    if: github.repository == 'meshery/meshery'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Fetch data for mesheryctl tag
        run: curl http://discuss.meshery.io/tag/mesheryctl.json -o docs/_data/discuss/mesheryctl.json
      - name: Fetch data for meshery tag
        run: curl http://discuss.meshery.io/tag/meshery.json -o docs/_data/discuss/meshery.json
      - name: Commit changes 
        uses: stefanzweifel/git-auto-commit-action@v4 
        with: 
          file_pattern: docs/_data/discuss/*.json
          commit_user_name: Discussions bot
          commit_user_email: discussions@meshery.io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: "--signoff"
          commit_message: "latest discussion data files added"
          branch: master
