name: Release Charts
on:
  push:
    branches:
      - 'master'
    paths:
      - 'install/kubernetes/**'
  pull_request:
    branches:
      - 'master'
    paths:
      - 'install/kubernetes/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.1
      - name: Helm lint
        env:
          CHARTS_PATH: install/kubernetes/helm
        run:
          helm lint ${{ env.CHARTS_PATH }}

  release:
    runs-on: ubuntu-latest
    needs: [lint-test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure Git
        env:
          GITHUB_ACTOR: l5io
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.1
      - name: Add dependency chart repos
        run: |
          helm repo add meshery https://meshery.io/charts/
      - name: Helm Chart Releaser For Remote
        uses: layer5io/helm-chart-releaser@v0.1.0
        with:
          charts_dir: charts
          owner: layer5io
          repo: meshery.io
          # For helm charts index
          charts_repo_url: https://meshery.io/charts/
          pages_branch: master
          activity: push
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Checkout target repo
        uses: actions/checkout@v2
        env:
          REPO: layer5io/meshery.io
          REPO_PATH: charts
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "${{ env.REPO }}"
          path: ${{ env.REPO_PATH }}
      - name: Copy index to new repo
        env:
          SOURCE: /home/runner/work/layer5io/meshery/install/kubernetes/helm/meshery/Chart.yaml
#          SOURCE: /home/runner/work/layer5io/meshery/.cr-index/index.yaml
          TARGET: meshery.io/charts
        run:
          cp ${{ env.SOURCE }} ${{ env.TARGET }}
      - name: Push
        env:
          REPO_PATH: meshery.io
          GIT_USERNAME: l5io
          GIT_EMAIL: l5io@users.noreply.github.com
        run: |
          cd ${{ env.REPO_PATH }}
          git config --local user.name "${{ env.GIT_USERNAME }}"
          git config --local user.email "${{ env.GIT_EMAIL }}"
          git add .
          git commit -s -m "Github Actions Automatically Built in `date +"%Y-%m-%d %H:%M"`"
          git push
