name: Release Charts
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
    paths:
      - 'install/kubernetes/**'
  pull_request:
    branches:
      - 'master'
    paths:
      - 'install/kubernetes/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      release-ver:
          description: 'Release Version'     
          required: false
          default: 'v'
jobs:
  validate:
    runs-on: ubuntu-latest
    if: ${{github.event_name == 'pull_request'}}
    steps:
    - uses: actions/checkout@v3
    - uses: azure/setup-helm@v2.0
      with:
        version: 'v3.6.0' # default is latest stable
      id: install
    - name: validate meshery
      run: helm lint install/kubernetes/helm/meshery --with-subcharts
    - name: validate meshery-operator
      run: helm lint install/kubernetes/helm/meshery-operator --with-subcharts
  release-chart:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }} && ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v3
      - name: set env
        id: vars
        # https://github.community/t/how-to-get-just-the-tag-name/16241/7
        run: echo ::set-output name=tag::${{ github.ref_name }}
      #- name: Publish Helm chart for edge latest
      #  if: startsWith(github.ref, 'refs/tags/') != true && success()
      #  uses: stefanprodan/helm-gh-pages@master
      #  with:
      #    token: ${{ secrets.GH_ACCESS_TOKEN }}
      #    charts_dir: install/kubernetes/helm
      #    owner: layer5io
      #    repository: meshery.io
      #    branch: master
      #    target_dir: charts
      #    commit_username: l5io
      #    commit_email: l5io@layer5.io
      #    chart_version: edge-latest
      #- name: Publish Helm chart for stable latest
      #  if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') && success()
      #  uses: stefanprodan/helm-gh-pages@master
      #  with:
      #    token: ${{ secrets.GH_ACCESS_TOKEN }}
      #    charts_dir: install/kubernetes/helm
      #    owner: layer5io
      #    repository: meshery.io
      #    branch: master
      #    target_dir: charts
      #    commit_username: l5io
      #    commit_email: l5io@layer5.io
      #    chart_version: stable-latest
      - name: Publish Helm chart for release version
        if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') && success()
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          charts_dir: install/kubernetes/helm
          owner: meshery
          repository: meshery.io
          branch: master
          target_dir: charts
          commit_username: l5io
          commit_email: l5io@layer5.io
          chart_version: ${{ steps.vars.outputs.tag }}
          app_version: ${{ steps.vars.outputs.tag }}
  
      - name: Manually publish Helm chart with release version
        if:  github.event_name != 'pull_request' && ${{github.event.inputs.release-ver}} != "v"
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          charts_dir: install/kubernetes/helm
          owner: meshery
          repository: meshery.io
          branch: master
          target_dir: charts
          commit_username: l5io
          commit_email: l5io@layer5.io
          chart_version: ${{github.event.inputs.release-ver}}
          app_version: ${{github.event.inputs.release-ver}}
