name: Meshery Docs CLI Reference Update
on:
  push:
    branches:
      - "master"
    paths:
      - "mesheryctl/**"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  mesheryctl_docs:
    if: "always() && github.event_name != 'pull_request' && github.repository == 'meshery/meshery' "
    runs-on: ubuntu-24.04
    steps:
      - name: Skip if needed
        run: |
          echo "this is it ${{ needs.SkipIfNeeded.outputs.skipdocupdate }} "
          if [ "${{github.event_name }}" == "push" ];then
            echo "version=edge" >> $GITHUB_ENV
          fi
          if [ "${{github.event_name }}" == "release" ];then
            echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v4
        with:
          repository: meshery/meshery
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          check-latest: "true"
      - name: Run script ðŸ“œ
        run: |
          cd mesheryctl
          make docs

      - name: Pull changes from remote
        run: git pull origin master

      - name: Commit âœ…
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: docs
          commit_user_name: l5io
          commit_user_email: ci@meshery.io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: "--signoff"
          commit_message: "[Docs] Update Meshery Docs CLI Reference"
