name: MeshModel Component Generator and Updater
on: 
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  run-script:
    name: Run Script
    if: github.repository == 'meshery/meshery'
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          fetch-depth: 1
          
      - name: Setup Go
        uses: actions/setup-go@master
        with:
          go-version: "1.20"
#       - name: Setup Cache
#         uses: actions/cache@v3
#         with:
#           path: ~/go/pkg/mod
#           key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
#           restore-keys: |
#             ${{ runner.os }}-go-
          
      - name: Run component generation (Along with spreadsheet updation)
        env:
          CRED: ${{ secrets.INTEGRATION_SPREADSHEET_CRED }}
        run: |
            cd scripts/component_generation; GOPROXY=https://proxy.golang.org,direct GOSUMDB=off go run main.go 1DZHnzxYWOlJ69Oguz4LkRVTFM79kC2tuvdwizOJmeMw
      - run: |
            cd scripts/component_updater; go build main.go; ./main https://docs.google.com/spreadsheets/d/e/2PACX-1vSgOXuiqbhUgtC9oNbJlz9PYpOEaFVoGNUFMIk4NZciFfQv1ewZg8ahdrWHKI79GkKK9TbmnZx8CqIe/pub\?gid\=0\&single\=true\&output\=csv --system meshery ../../server/meshmodel/components
      - name: Commit changes 
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: l5io
          commit_user_email: ci@layer5.io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: "--signoff"
          commit_message: "New Meshmodel components generated"
          branch: master
