name: Multiversion k8s e2e tests
on:
  # if manually triggering, provide a provider token yourself
  workflow_dispatch:
    inputs:
      provider_token:
        description: "token for remote provider"
        required: false
      profile_name:
        description: "name of the performance profile to use"
        required: false
        default: SMP_CRON_ISTIO
  # runs at 43 minutes of every 12th hour
  # gh receives too many requests at "perfect times" e.g 00:00, 00:30
  # and ends up dropping a lot of them this arbitrary time will ensure
  # availablility
  schedule:
    - cron: '43 */12 * * *'

# these jobs deploy a minikube cluster with k8s versions 1.20, 1.21, 1.22
# uses meshery, meshery-adapters edge-latest and mesheryctl stable-latest

# manual-job is triggered manually in case of problems with provider tokens
jobs:
  in-cluster-manual:
    name: Triggered in-cluster tests manually
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    strategy:
      fail-fast: false
      matrix:
        k8s_versions: ['v1.20.11', 'v1.21.5', 'v1.22.2']
    steps:
      - name: Deploy k8s
        uses: manusa/actions-setup-minikube@v2.4.1
        with:
          minikube version: 'v1.23.2'
          kubernetes version: ${{ matrix.k8s_versions }}
          driver: docker

      - name: Test using meshery-smp-action
        uses: layer5io/meshery-smp-action@meshery-ci
        with:
          provider_token: ${{ github.event.inputs.provider_token }}
          platform: kubernetes
          profile_name: ${{ github.event.inputs.profile_name }}

  out-of-cluster-manual:
    name: Triggered out-of-cluster tests manually
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    strategy:
      fail-fast: false
      matrix:
        k8s_versions: ['v1.20.11', 'v1.21.5', 'v1.22.2']
    steps:
      - name: Deploy k8s
        uses: manusa/actions-setup-minikube@v2.4.1
        with:
          minikube version: 'v1.23.2'
          kubernetes version: ${{ matrix.k8s_versions }}
          driver: docker

      - name: Test using meshery-smp-action
        uses: layer5io/meshery-smp-action@meshery-ci
        with:
          provider_token: ${{ github.event.inputs.provider_token }}
          platform: docker
          profile_name: ${{ github.event.inputs.profile_name }}

# auto-job is triggered with a cron scehdule
  in-cluster-scheduled:
    name: Scheduled in-cluster tests
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' }}
    strategy:
      fail-fast: false
      matrix:
        k8s_versions: ['v1.20.11', 'v1.21.5', 'v1.22.2']
    steps:
      - name: Deploy k8s
        uses: manusa/actions-setup-minikube@v2.4.1
        with:
          minikube version: 'v1.23.2'
          kubernetes version: ${{ matrix.k8s_versions }}
          driver: docker

      - name: Test using meshery-smp-action
        uses: layer5io/meshery-smp-action@meshery-ci
        with:
          provider_token: ${{ secrets.provider_token }}
          platform: kubernetes
          profile_name: SMP_CRON_ISTIO

  out-of-cluster-scheduled:
    name: Scheduled out-of-cluster tests
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' }}
    strategy:
      fail-fast: false
      matrix:
        k8s_versions: ['v1.20.11', 'v1.21.5', 'v1.22.2']
    steps:
      - name: Deploy k8s
        uses: manusa/actions-setup-minikube@v2.4.1
        with:
          minikube version: 'v1.23.2'
          kubernetes version: ${{ matrix.k8s_versions }}
          driver: docker

      - name: Test using meshery-smp-action
        uses: layer5io/meshery-smp-action@meshery-ci
        with:
          provider_token: ${{ secrets.provider_token }}
          platform: docker
          profile_name: SMP_CRON_ISTIO
