name: Notify Remote Providers
on:
  push:
    branches:
      - '!*'
    tags:
      - 'v*'

jobs:
  notify-meshmap-build:
    name: Notify Meshmap Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger plugins for edge
      if: startsWith(github.ref, 'refs/tags/') != true && success()
      uses: layer5io/trigger-remote-provider-action@master
      with:
        name: "Build and Publish"
        repo: layer5labs/meshery-extensions
        token: ${{ secrets.GH_ACCESS_TOKEN }}
        version: master
    - name: trigger plugins for release
      if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') && success()
      uses: layer5io/trigger-remote-provider-action@master
      with:
        name: "Build and Publish"
        repo: layer5labs/meshery-extensions
        token: ${{ secrets.GH_ACCESS_TOKEN }}
        version: ${GITHUB_REF/refs\/tags\//}
